import os
import hashlib
import re

RAW_DIR = "data/raw"
CLEAN_DIR = "data/cleaned"

REMOVE_DIRS = {
    "tests", "test", "docs", "doc", "examples", "example",
    ".github", ".git", "__pycache__", "scripts", "script",
    "migrations", "migration", "build", "dist",
    ".vscode", ".idea", "ci", "coverage"
}

MAX_FILE_SIZE = 500_000
MAX_LINES = 1500
MIN_LINES = 5

AUTO_GEN_PATTERNS = [
    "auto-generated",
    "autogenerated",
    "do not edit",
    "generated by",
    "sphinx",
]

def is_bad_dir(name):
    return name.lower() in REMOVE_DIRS

def is_bad_file(name):
    name = name.lower()
    if not name.endswith(".py"):
        return True
    if name.startswith("test_") or name.endswith("_test.py"):
        return True
    return False

def is_autogenerated(text):
    lower = text.lower()
    return any(pattern in lower for pattern in AUTO_GEN_PATTERNS)

def strip_large_docstring(text):
    pattern = r'^\s*(\"\"\".*?\"\"\"|\'\'\'.*?\'\'\')'
    match = re.match(pattern, text, flags=re.DOTALL)
    if match and match.group(0).count("\n") > 20:
        text = text[len(match.group(0)):]
    return text.strip()

def file_hash(text):
    return hashlib.md5(text.encode("utf-8")).hexdigest()

def clear_cleaned_folder():
    if not os.path.exists(CLEAN_DIR):
        os.makedirs(CLEAN_DIR)
        return

    for root, dirs, files in os.walk(CLEAN_DIR):
        for file in files:
            try:
                os.remove(os.path.join(root, file))
            except:
                pass

def clean():
    clear_cleaned_folder()

    seen_hashes = set()
    kept = 0
    skipped = 0

    for root, dirs, files in os.walk(RAW_DIR, topdown=True):
        dirs[:] = [d for d in dirs if not is_bad_dir(d)]

        for file in files:
            if is_bad_file(file):
                skipped += 1
                continue

            path = os.path.join(root, file)

            if os.path.getsize(path) > MAX_FILE_SIZE:
                skipped += 1
                continue

            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    text = f.read()
            except:
                skipped += 1
                continue

            lines = text.splitlines()
            if len(lines) < MIN_LINES or len(lines) > MAX_LINES:
                skipped += 1
                continue

            if is_autogenerated(text):
                skipped += 1
                continue

            text = strip_large_docstring(text)

            if len(text.strip()) < 50:
                skipped += 1
                continue

            h = file_hash(text)
            if h in seen_hashes:
                skipped += 1
                continue

            seen_hashes.add(h)

            rel_path = os.path.relpath(path, RAW_DIR)
            dest_path = os.path.join(CLEAN_DIR, rel_path)

            os.makedirs(os.path.dirname(dest_path), exist_ok=True)

            try:
                with open(dest_path, "w", encoding="utf-8") as out:
                    out.write(text)
                kept += 1
            except:
                skipped += 1

    print("===== CLEANING COMPLETE =====")
    print(f"Files kept: {kept}")
    print(f"Files skipped: {skipped}")

if __name__ == "__main__":
    clean()